/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using Bitcasa.PCL.Controllers;
using Bitcasa.PCL.Http.Client;

namespace Bitcasa.PCL
{
    public partial class BitcasaClient
    {

        /// <summary>
        /// Singleton access to UserOperations controller
        /// </summary>
        public UserOperationsController UserOperations
        {
            get
            {
                return UserOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to CreateAccount controller
        /// </summary>
        public CreateAccountController CreateAccount
        {
            get
            {
                return CreateAccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to FileOperations controller
        /// </summary>
        public FileOperationsController FileOperations
        {
            get
            {
                return FileOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to FoldersOperations controller
        /// </summary>
        public FoldersOperationsController FoldersOperations
        {
            get
            {
                return FoldersOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ShareOperations controller
        /// </summary>
        public ShareOperationsController ShareOperations
        {
            get
            {
                return ShareOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to HistoryOperations controller
        /// </summary>
        public HistoryOperationsController HistoryOperations
        {
            get
            {
                return HistoryOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to TrashOperations controller
        /// </summary>
        public TrashOperationsController TrashOperations
        {
            get
            {
                return TrashOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to AdministratorsOperations controller
        /// </summary>
        public AdministratorsOperationsController AdministratorsOperations
        {
            get
            {
                return AdministratorsOperationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to AuthenticationOperations controller
        /// </summary>
        public AuthenticationOperationsController AuthenticationOperations
        {
            get
            {
                return AuthenticationOperationsController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public BitcasaClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public BitcasaClient(string accountId, string oAuthAccessToken)
        {
            Configuration.AccountId = accountId;
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}