/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;

namespace Bitcasa.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://{0}.cloudfs.io";

        //TODO: Replace the AccountId with an appropriate value
        public static string AccountId = "TODO: Replace";

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the OAuthAccessToken with an appropriate value
        public static string OAuthAccessToken = "TODO: Replace";

    }
}