/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Bitcasa.PCL;

namespace Bitcasa.PCL.Models
{
    public class AuthenticationResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accessToke;
        private string tokenType;
        private string error;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("access_toke")]
        public string AccessToke 
        { 
            get 
            {
                return this.accessToke; 
            } 
            set 
            {
                this.accessToke = value;
                onPropertyChanged("AccessToke");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("token_type")]
        public string TokenType 
        { 
            get 
            {
                return this.tokenType; 
            } 
            set 
            {
                this.tokenType = value;
                onPropertyChanged("TokenType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error")]
        public string Error 
        { 
            get 
            {
                return this.error; 
            } 
            set 
            {
                this.error = value;
                onPropertyChanged("Error");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 