/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Bitcasa.PCL;

namespace Bitcasa.PCL.Models
{
    public class Data : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string shareKey;
        private string exists;
        private List<string> path;
        private string shareUrl;
        private string id;
        private string applicationData;
        private string name;
        private DateTime dateCreated;
        private string to;
        private string parentId;
        private DateTime dateMetaLastModified;
        private DateTime dateContentLastModified;
        private int size;
        private string mime;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("share_key")]
        public string ShareKey 
        { 
            get 
            {
                return this.shareKey; 
            } 
            set 
            {
                this.shareKey = value;
                onPropertyChanged("ShareKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("exists")]
        public string Exists 
        { 
            get 
            {
                return this.exists; 
            } 
            set 
            {
                this.exists = value;
                onPropertyChanged("Exists");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("path")]
        public List<string> Path 
        { 
            get 
            {
                return this.path; 
            } 
            set 
            {
                this.path = value;
                onPropertyChanged("Path");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("share_url")]
        public string ShareUrl 
        { 
            get 
            {
                return this.shareUrl; 
            } 
            set 
            {
                this.shareUrl = value;
                onPropertyChanged("ShareUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("application_data")]
        public string ApplicationData 
        { 
            get 
            {
                return this.applicationData; 
            } 
            set 
            {
                this.applicationData = value;
                onPropertyChanged("ApplicationData");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("date_created")]
        public DateTime DateCreated 
        { 
            get 
            {
                return this.dateCreated; 
            } 
            set 
            {
                this.dateCreated = value;
                onPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("parent_id")]
        public string ParentId 
        { 
            get 
            {
                return this.parentId; 
            } 
            set 
            {
                this.parentId = value;
                onPropertyChanged("ParentId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("date_meta_last_modified")]
        public DateTime DateMetaLastModified 
        { 
            get 
            {
                return this.dateMetaLastModified; 
            } 
            set 
            {
                this.dateMetaLastModified = value;
                onPropertyChanged("DateMetaLastModified");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("date_content_last_modified")]
        public DateTime DateContentLastModified 
        { 
            get 
            {
                return this.dateContentLastModified; 
            } 
            set 
            {
                this.dateContentLastModified = value;
                onPropertyChanged("DateContentLastModified");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("size")]
        public int Size 
        { 
            get 
            {
                return this.size; 
            } 
            set 
            {
                this.size = value;
                onPropertyChanged("Size");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mime")]
        public string Mime 
        { 
            get 
            {
                return this.mime; 
            } 
            set 
            {
                this.mime = value;
                onPropertyChanged("Mime");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 