/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Bitcasa.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ExistsEnum
    {
        FAIL, //TODO: Write general description for this method
        OVERWRITE, //TODO: Write general description for this method
        RENAME, //TODO: Write general description for this method
        REUSE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ExistsEnum
    /// </summary>
    public static class ExistsEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "fail", "overwrite", "rename", "reuse" };

        /// <summary>
        /// Converts a ExistsEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ExistsEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ExistsEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ExistsEnum.FAIL:
                case ExistsEnum.OVERWRITE:
                case ExistsEnum.RENAME:
                case ExistsEnum.REUSE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ExistsEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ExistsEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ExistsEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ExistsEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ExistsEnum value</returns>
        public static ExistsEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ExistsEnum", value));

            return (ExistsEnum) index;
        }
    }
} 