/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Bitcasa.PCL;

namespace Bitcasa.PCL.Models
{
    public class Holds : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool deleted;
        private bool otl;
        private bool suspended;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deleted")]
        public bool Deleted 
        { 
            get 
            {
                return this.deleted; 
            } 
            set 
            {
                this.deleted = value;
                onPropertyChanged("Deleted");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("otl")]
        public bool Otl 
        { 
            get 
            {
                return this.otl; 
            } 
            set 
            {
                this.otl = value;
                onPropertyChanged("Otl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("suspended")]
        public bool Suspended 
        { 
            get 
            {
                return this.suspended; 
            } 
            set 
            {
                this.suspended = value;
                onPropertyChanged("Suspended");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 