/*
 * Bitcasa.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

using Bitcasa.PCL;

namespace Bitcasa.PCL.Models
{
    public class VersionConflict : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string fail;
        private string ignore;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fail")]
        public string Fail 
        { 
            get 
            {
                return this.fail; 
            } 
            set 
            {
                this.fail = value;
                onPropertyChanged("Fail");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ignore")]
        public string Ignore 
        { 
            get 
            {
                return this.ignore; 
            } 
            set 
            {
                this.ignore = value;
                onPropertyChanged("Ignore");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 